import type { TechnologyDefinition } from '../civilizationTypes';

export const CORE_TECHNOLOGIES: TechnologyDefinition[] = [
  { id: 'controlled-fire', name: 'Управляемый огонь', eraId: 'survival', category: 'выживание', prerequisites: [], cost: 0, unlocks: { capabilities: ['cooking', 'heating'] }, description: 'Очаги, обогрев, простая готовка и термическая обработка материалов.' },
  { id: 'oral-tradition', name: 'Устная традиция', eraId: 'survival', category: 'знания', prerequisites: [], cost: 0, unlocks: { capabilities: ['oral-memory'] }, description: 'Община сохраняет правила, маршруты и опыт через живых носителей.' },
  { id: 'settled-agriculture', name: 'Оседлое земледелие', eraId: 'settlement', category: 'земледелие', prerequisites: ['controlled-fire'], cost: 85, requirements: { minimumPopulation: 35 }, unlocks: { capabilities: ['fields', 'seed-selection'] }, description: 'Поля, семенные запасы и повторяемые циклы посева превращают поселение в устойчивое хозяйство.' },
  { id: 'animal-husbandry', name: 'Животноводство', eraId: 'settlement', category: 'земледелие', prerequisites: ['controlled-fire'], cost: 70, requirements: { minimumPopulation: 30 }, unlocks: { capabilities: ['livestock-breeding'] }, description: 'Содержание скота даёт молоко, яйца, шерсть, кожу и тягловую силу.' },
  { id: 'food-preservation', name: 'Сохранение пищи', eraId: 'settlement', category: 'ремесло', prerequisites: ['controlled-fire'], cost: 65, unlocks: { capabilities: ['smoking', 'salting', 'drying'] }, description: 'Копчение, засолка и сушение уменьшают сезонный голод и делают дальнюю торговлю возможной.' },
  { id: 'carpentry', name: 'Плотницкое ремесло', eraId: 'settlement', category: 'ремесло', prerequisites: ['controlled-fire'], cost: 75, unlocks: { capabilities: ['timber-framing', 'woodworking'] }, description: 'Обработанная древесина становится основой жилья, мебели, инструментов и транспорта.' },
  { id: 'textile-craft', name: 'Текстильное ремесло', eraId: 'settlement', category: 'ремесло', prerequisites: ['animal-husbandry'], cost: 90, unlocks: { capabilities: ['spinning', 'weaving', 'tailoring'] }, description: 'Прядение, ткачество, красители и пошив создают устойчивую одежду и торговые товары.' },
  { id: 'fermentation', name: 'Брожение', eraId: 'settlement', category: 'ремесло', prerequisites: ['settled-agriculture'], cost: 70, unlocks: { capabilities: ['brewing', 'winemaking'] }, description: 'Контролируемое брожение создаёт напитки, которые можно хранить и продавать.' },
  { id: 'masonry', name: 'Каменное строительство', eraId: 'urban', category: 'строительство', prerequisites: ['carpentry'], cost: 135, requirements: { minimumUrbanization: 18, requiredResourceIds: ['stone'] }, unlocks: { capabilities: ['stone-buildings', 'kilns', 'lime-mortar'] }, description: 'Камень, кирпич и известь позволяют строить долговечные общественные здания и укрепления.' },
  { id: 'metalworking', name: 'Обработка железа', eraId: 'urban', category: 'ремесло', prerequisites: ['controlled-fire'], cost: 145, requirements: { minimumPopulation: 140, requiredResourceIds: ['iron_ore'] }, unlocks: { capabilities: ['smelting', 'forging'] }, description: 'Руда, древесный уголь и кузнечное мастерство создают железо, оружие и крепёж.' },
  { id: 'specialized-tools', name: 'Специализированные инструменты', eraId: 'urban', category: 'ремесло', prerequisites: ['metalworking', 'carpentry'], cost: 125, requirements: { minimumProsperity: 25 }, unlocks: { capabilities: ['precision-tools', 'workshop-specialization'] }, description: 'Отдельные инструменты для каждой профессии повышают производительность и качество.' },
  { id: 'written-records', name: 'Письменный учёт', eraId: 'urban', category: 'знания', prerequisites: ['oral-tradition'], cost: 150, requirements: { minimumLiteracy: 8 }, unlocks: { capabilities: ['books', 'archives', 'contracts'] }, description: 'Письмо отделяет знание от памяти одного человека и позволяет вести долговременный учёт.' },
  { id: 'mechanical-milling', name: 'Механический помол', eraId: 'urban', category: 'ремесло', prerequisites: ['settled-agriculture', 'carpentry'], cost: 105, unlocks: { capabilities: ['mills'] }, description: 'Мельницы стабильно превращают зерно в муку и поддерживают крупные поселения.' },
  { id: 'civic-planning', name: 'Городское планирование', eraId: 'urban', category: 'управление', prerequisites: ['masonry', 'written-records'], cost: 180, requirements: { minimumUrbanization: 30 }, unlocks: { capabilities: ['district-planning', 'public-works'] }, description: 'Власть учитывает землю, воду, улицы, склады, жильё и общественные службы как единую систему.' },
  { id: 'guild-organization', name: 'Гильдейская организация', eraId: 'scholarship', category: 'управление', prerequisites: ['written-records', 'specialized-tools'], cost: 210, requirements: { minimumUrbanization: 40, minimumLiteracy: 18 }, unlocks: { capabilities: ['guilds', 'apprenticeship-standards'] }, description: 'Гильдии закрепляют обучение, качество, цены и передачу сложных ремёсел.' },
  { id: 'formal-medicine', name: 'Систематическая медицина', eraId: 'scholarship', category: 'знания', prerequisites: ['written-records', 'food-preservation'], cost: 220, requirements: { minimumLiteracy: 22 }, unlocks: { capabilities: ['medical-records', 'trained-healers'] }, description: 'Наблюдения, записи и обучение превращают лечение в накапливаемую практику.' },
  { id: 'advanced-armoring', name: 'Сложное защитное снаряжение', eraId: 'scholarship', category: 'военное дело', prerequisites: ['metalworking', 'guild-organization'], cost: 230, requirements: { minimumProsperity: 38 }, unlocks: { capabilities: ['advanced-armor', 'standardized-arms'] }, description: 'Специализированные мастерские делают составные доспехи и стандартизированное вооружение.' },
  { id: 'arcane-method', name: 'Арканный метод', eraId: 'arcane', category: 'магия', prerequisites: ['written-records', 'formal-medicine'], cost: 320, requirements: { minimumMagic: .55, minimumLiteracy: 34 }, unlocks: { capabilities: ['repeatable-magic', 'arcane-schools'] }, description: 'Магические эффекты описываются, повторяются и передаются через школы и проверяемые процедуры.' },
];
