import type { ProductionRecipe } from '../types';
import type { RecipeDefinition } from '../civilizationTypes';

const RAW_RECIPES: Omit<ProductionRecipe, 'id' | 'key' | 'requiredTechnologyId'>[] = [
  { name: 'Сбор хвороста и дров', category: 'добыча', profession: 'farmer', establishmentTypes: ['ферма'], inputs: [], outputs: [{ templateId: 'firewood', quantity: 6 }], laborHours: 8, minimumSkill: 5, description: 'Сельские дворы заготавливают топливо в окрестных лесах и изгородях.' },
  { name: 'Заготовка древесины', category: 'добыча', profession: 'carpenter', establishmentTypes: ['плотницкая мастерская'], inputs: [], outputs: [{ templateId: 'timber', quantity: 5 }, { templateId: 'firewood', quantity: 7 }], laborHours: 22, minimumSkill: 12, description: 'Лес превращается в брёвна и топливо.' },
  { name: 'Рыбный промысел', category: 'добыча', profession: 'fisher', establishmentTypes: ['рыбный промысел'], inputs: [], outputs: [{ templateId: 'fish', quantity: 8 }], laborHours: 18, minimumSkill: 8, description: 'Рыбаки возвращаются с уловом.' },
  { name: 'Добыча железной руды', category: 'добыча', profession: 'miner', establishmentTypes: ['рудник'], inputs: [], outputs: [{ templateId: 'iron_ore', quantity: 6 }, { templateId: 'stone', quantity: 4 }], laborHours: 26, minimumSkill: 12, description: 'Шахтёры добывают руду и камень.' },
  { name: 'Помол муки', category: 'переработка', profession: 'miller', establishmentTypes: ['мельница'], inputs: [{ templateId: 'grain', quantity: 4 }], outputs: [{ templateId: 'flour', quantity: 4 }], laborHours: 8, minimumSkill: 8, description: 'Мельница превращает зерно в муку.' },
  { name: 'Выпечка хлеба', category: 'готовка', profession: 'baker', establishmentTypes: ['пекарня'], inputs: [{ templateId: 'flour', quantity: 2 }, { templateId: 'firewood', quantity: 1 }], outputs: [{ templateId: 'bread', quantity: 18 }], laborHours: 10, minimumSkill: 12, description: 'Пекари выпекают ежедневный хлеб.' },
  { name: 'Похлёбка', category: 'готовка', profession: 'cook', establishmentTypes: ['таверна', 'постоялый двор'], inputs: [{ templateId: 'vegetables', quantity: 2 }, { templateId: 'grain', quantity: 1 }, { templateId: 'firewood', quantity: 1 }], outputs: [{ templateId: 'stew', quantity: 14 }], laborHours: 7, minimumSkill: 7, description: 'Дешёвая горячая пища для жителей и путников.' },
  { name: 'Мясное жаркое', category: 'готовка', profession: 'cook', establishmentTypes: ['таверна', 'постоялый двор'], inputs: [{ templateId: 'meat', quantity: 1 }, { templateId: 'vegetables', quantity: 1 }, { templateId: 'firewood', quantity: 1 }], outputs: [{ templateId: 'roast', quantity: 10 }], laborHours: 9, minimumSkill: 16, description: 'Сытное блюдо из мяса и овощей.' },
  { name: 'Копчение мяса', category: 'переработка', profession: 'cook', establishmentTypes: ['таверна', 'склад'], inputs: [{ templateId: 'meat', quantity: 2 }, { templateId: 'firewood', quantity: 1 }], outputs: [{ templateId: 'smoked_meat', quantity: 4 }], laborHours: 12, minimumSkill: 12, description: 'Мясо хранится дольше после копчения.' },
  { name: 'Засолка рыбы', category: 'переработка', profession: 'fisher', establishmentTypes: ['рыбный промысел', 'склад'], inputs: [{ templateId: 'fish', quantity: 2 }, { templateId: 'salt', quantity: 1 }], outputs: [{ templateId: 'salted_fish', quantity: 3 }], laborHours: 8, minimumSkill: 10, description: 'Рыбу засаливают для долгого пути.' },
  { name: 'Варка эля', category: 'переработка', profession: 'brewer', establishmentTypes: ['пивоварня'], inputs: [{ templateId: 'grain', quantity: 3 }, { templateId: 'firewood', quantity: 1 }], outputs: [{ templateId: 'ale', quantity: 28 }], laborHours: 20, minimumSkill: 14, description: 'Пивоварня превращает зерно в эль.' },
  { name: 'Виноделие', category: 'переработка', profession: 'brewer', establishmentTypes: ['винодельня'], inputs: [{ templateId: 'fruit', quantity: 4 }], outputs: [{ templateId: 'wine', quantity: 8 }], laborHours: 24, minimumSkill: 18, description: 'Фрукты бродят и становятся вином.' },
  { name: 'Выплавка железа', category: 'переработка', profession: 'blacksmith', establishmentTypes: ['кузница'], inputs: [{ templateId: 'iron_ore', quantity: 3 }, { templateId: 'charcoal', quantity: 2 }], outputs: [{ templateId: 'iron', quantity: 2 }], laborHours: 18, minimumSkill: 18, description: 'Руда превращается в пригодное железо.' },
  { name: 'Ковка инструментов', category: 'ремесло', profession: 'blacksmith', establishmentTypes: ['кузница'], inputs: [{ templateId: 'iron', quantity: 1 }, { templateId: 'timber', quantity: 1 }], outputs: [{ templateId: 'tools', quantity: 1 }], laborHours: 14, minimumSkill: 20, description: 'Кузнец делает инструменты для других ремёсел.' },
  { name: 'Ковка оружия', category: 'ремесло', profession: 'blacksmith', establishmentTypes: ['кузница'], inputs: [{ templateId: 'iron', quantity: 2 }, { templateId: 'timber', quantity: 1 }], outputs: [{ templateId: 'weapon', quantity: 1, qualityBonus: 5 }], laborHours: 22, minimumSkill: 28, description: 'Оружие требует больше железа и мастерства.' },
  { name: 'Изготовление мебели', category: 'ремесло', profession: 'carpenter', establishmentTypes: ['плотницкая мастерская'], inputs: [{ templateId: 'timber', quantity: 2 }, { templateId: 'tools', quantity: .05 }], outputs: [{ templateId: 'furniture', quantity: 1 }], laborHours: 18, minimumSkill: 18, description: 'Плотники делают кровати, столы и сундуки.' },
  { name: 'Ткачество', category: 'переработка', profession: 'weaver', establishmentTypes: ['ткацкая мастерская'], inputs: [{ templateId: 'wool', quantity: 2 }], outputs: [{ templateId: 'cloth', quantity: 2 }], laborHours: 16, minimumSkill: 14, description: 'Шерсть превращается в ткань.' },
  { name: 'Пошив одежды', category: 'ремесло', profession: 'weaver', establishmentTypes: ['ткацкая мастерская'], inputs: [{ templateId: 'cloth', quantity: 2 }], outputs: [{ templateId: 'clothes', quantity: 1 }], laborHours: 15, minimumSkill: 18, description: 'Ткань превращается в одежду.' },
  { name: 'Помол пшеницы', category: 'переработка', profession: 'miller', establishmentTypes: ['мельница'], inputs: [{ templateId: 'wheat', quantity: 4 }], outputs: [{ templateId: 'flour', quantity: 4 }], laborHours: 8, minimumSkill: 8, description: 'Пшеница превращается в хлебную муку.' },
  { name: 'Помол ржи', category: 'переработка', profession: 'miller', establishmentTypes: ['мельница'], inputs: [{ templateId: 'rye', quantity: 4 }], outputs: [{ templateId: 'flour', quantity: 3 }], laborHours: 9, minimumSkill: 8, description: 'Рожь превращается в тёмную муку.' },
  { name: 'Ячменный солод', category: 'переработка', profession: 'brewer', establishmentTypes: ['пивоварня'], inputs: [{ templateId: 'barley', quantity: 3 }, { templateId: 'firewood', quantity: 1 }], outputs: [{ templateId: 'ale', quantity: 30 }], laborHours: 20, minimumSkill: 14, description: 'Ячмень проращивают, сушат и варят в эль.' },
  { name: 'Распиловка досок', category: 'переработка', profession: 'carpenter', establishmentTypes: ['плотницкая мастерская'], inputs: [{ templateId: 'timber', quantity: 2 }], outputs: [{ templateId: 'planks', quantity: 3 }], laborHours: 12, minimumSkill: 14, description: 'Брёвна распускают на строительные доски.' },
  { name: 'Обжиг кирпича', category: 'переработка', profession: 'carpenter', establishmentTypes: ['кирпичная мастерская'], inputs: [{ templateId: 'clay', quantity: 3 }, { templateId: 'firewood', quantity: 2 }], outputs: [{ templateId: 'bricks', quantity: 3 }], laborHours: 18, minimumSkill: 12, description: 'Глину формуют и обжигают в печи.' },
  { name: 'Обжиг извести', category: 'переработка', profession: 'miner', establishmentTypes: ['кирпичная мастерская'], inputs: [{ templateId: 'stone', quantity: 3 }, { templateId: 'firewood', quantity: 2 }], outputs: [{ templateId: 'lime', quantity: 2 }], laborHours: 20, minimumSkill: 16, description: 'Известняк обжигают для строительного раствора.' },
  { name: 'Ковка гвоздей', category: 'ремесло', profession: 'blacksmith', establishmentTypes: ['кузница'], inputs: [{ templateId: 'iron', quantity: 1 }, { templateId: 'charcoal', quantity: 1 }], outputs: [{ templateId: 'nails', quantity: 4 }], laborHours: 12, minimumSkill: 18, description: 'Кузнец делает крепёж для стройки и кораблей.' },
  { name: 'Витьё верёвки', category: 'ремесло', profession: 'weaver', establishmentTypes: ['ткацкая мастерская'], inputs: [{ templateId: 'flax', quantity: 2 }], outputs: [{ templateId: 'rope', quantity: 2 }], laborHours: 12, minimumSkill: 14, description: 'Льняное волокно превращается в прочную верёвку.' },
  { name: 'Добыча глины и камня', category: 'добыча', profession: 'miner', establishmentTypes: ['каменоломня'], inputs: [], outputs: [{ templateId: 'clay', quantity: 5 }, { templateId: 'stone', quantity: 4 }], laborHours: 24, minimumSkill: 10, description: 'Рабочие снимают глину и добывают строительный камень.' },
  { name: 'Трепание льна', category: 'переработка', profession: 'weaver', establishmentTypes: ['ткацкая мастерская'], inputs: [{ templateId: 'flax', quantity: 2 }], outputs: [{ templateId: 'flax_fiber', quantity: 2 }], laborHours: 12, minimumSkill: 10, description: 'Лён вымачивают, сушат и превращают в волокно.' },
  { name: 'Прядение льняной нити', category: 'переработка', profession: 'weaver', establishmentTypes: ['ткацкая мастерская'], inputs: [{ templateId: 'flax_fiber', quantity: 2 }], outputs: [{ templateId: 'linen_thread', quantity: 2 }], laborHours: 12, minimumSkill: 12, description: 'Волокно прядут в ровную льняную нить.' },
  { name: 'Ткачество льняной ткани', category: 'переработка', profession: 'weaver', establishmentTypes: ['ткацкая мастерская'], inputs: [{ templateId: 'linen_thread', quantity: 3 }], outputs: [{ templateId: 'linen_cloth', quantity: 2 }], laborHours: 18, minimumSkill: 16, description: 'Нить превращается в прочную льняную ткань.' },
  { name: 'Прядение шерсти', category: 'переработка', profession: 'weaver', establishmentTypes: ['ткацкая мастерская'], inputs: [{ templateId: 'wool', quantity: 2 }], outputs: [{ templateId: 'wool_yarn', quantity: 2 }], laborHours: 12, minimumSkill: 12, description: 'Очищенную шерсть превращают в пряжу.' },
  { name: 'Ткачество шерстяной ткани', category: 'переработка', profession: 'weaver', establishmentTypes: ['ткацкая мастерская'], inputs: [{ templateId: 'wool_yarn', quantity: 3 }], outputs: [{ templateId: 'wool_cloth', quantity: 2 }], laborHours: 18, minimumSkill: 16, description: 'Шерстяную пряжу ткут в тёплую ткань.' },
  { name: 'Дубление кожи', category: 'переработка', profession: 'tanner', establishmentTypes: ['кожевенная мастерская'], inputs: [{ templateId: 'raw_hide', quantity: 2 }, { templateId: 'salt', quantity: 1 }], outputs: [{ templateId: 'leather', quantity: 2 }], laborHours: 24, minimumSkill: 14, description: 'Шкуры очищают и дубят для обуви, ремней и брони.' },
  { name: 'Синий краситель из вайды', category: 'переработка', profession: 'dyer', establishmentTypes: ['красильня'], inputs: [{ templateId: 'flax', quantity: 1 }], outputs: [{ templateId: 'dye_blue', quantity: 2 }], laborHours: 14, minimumSkill: 14, description: 'Красильщики получают стойкий синий пигмент.' },
  { name: 'Красный краситель из марены', category: 'переработка', profession: 'dyer', establishmentTypes: ['красильня'], inputs: [{ templateId: 'vegetables', quantity: 1 }], outputs: [{ templateId: 'dye_red', quantity: 2 }], laborHours: 14, minimumSkill: 14, description: 'Корни марены дают красный пигмент.' },
  { name: 'Льняная одежда', category: 'ремесло', profession: 'tailor', establishmentTypes: ['портная мастерская'], inputs: [{ templateId: 'linen_cloth', quantity: 3 }], outputs: [{ templateId: 'linen_hood', quantity: 1 }, { templateId: 'linen_shirt', quantity: 1 }], laborHours: 20, minimumSkill: 16, description: 'Портной шьёт повседневную льняную одежду.' },
  { name: 'Шерстяная одежда', category: 'ремесло', profession: 'tailor', establishmentTypes: ['портная мастерская'], inputs: [{ templateId: 'wool_cloth', quantity: 4 }], outputs: [{ templateId: 'wool_tunic', quantity: 1 }, { templateId: 'wool_trousers', quantity: 1 }, { templateId: 'wool_cloak', quantity: 1 }], laborHours: 30, minimumSkill: 20, description: 'Портной шьёт тёплый комплект одежды.' },
  { name: 'Кожаная обувь и перчатки', category: 'ремесло', profession: 'cobbler', establishmentTypes: ['сапожная мастерская'], inputs: [{ templateId: 'leather', quantity: 3 }], outputs: [{ templateId: 'leather_shoes', quantity: 1 }, { templateId: 'leather_gloves', quantity: 1 }], laborHours: 22, minimumSkill: 18, description: 'Сапожник делает обувь и рабочие перчатки.' },
  { name: 'Стёганый доспех', category: 'ремесло', profession: 'armorer', establishmentTypes: ['бронная мастерская'], inputs: [{ templateId: 'linen_cloth', quantity: 4 }, { templateId: 'wool', quantity: 2 }], outputs: [{ templateId: 'padded_cap', quantity: 1 }, { templateId: 'gambeson', quantity: 1 }], laborHours: 34, minimumSkill: 24, description: 'Бронник шьёт защитный стёганый комплект.' },
  { name: 'Кожаный доспех', category: 'ремесло', profession: 'armorer', establishmentTypes: ['бронная мастерская'], inputs: [{ templateId: 'leather', quantity: 5 }, { templateId: 'iron', quantity: 1 }], outputs: [{ templateId: 'leather_armor', quantity: 1 }], laborHours: 36, minimumSkill: 28, description: 'Кожа усиливается металлическими пластинами.' },
  { name: 'Кольчуга', category: 'ремесло', profession: 'armorer', establishmentTypes: ['бронная мастерская'], inputs: [{ templateId: 'iron', quantity: 8 }, { templateId: 'charcoal', quantity: 3 }], outputs: [{ templateId: 'chainmail', quantity: 1 }], laborHours: 80, minimumSkill: 42, description: 'Тысячи колец соединяются в тяжёлую кольчугу.' },
  { name: 'Шлем и щит', category: 'ремесло', profession: 'armorer', establishmentTypes: ['бронная мастерская'], inputs: [{ templateId: 'iron', quantity: 3 }, { templateId: 'planks', quantity: 2 }, { templateId: 'leather', quantity: 1 }], outputs: [{ templateId: 'iron_helmet', quantity: 1 }, { templateId: 'wooden_shield', quantity: 1 }], laborHours: 36, minimumSkill: 30, description: 'Бронник делает шлем и щит.' },
  { name: 'Ковка копья', category: 'ремесло', profession: 'blacksmith', establishmentTypes: ['оружейная лавка', 'кузница'], inputs: [{ templateId: 'iron', quantity: 1 }, { templateId: 'timber', quantity: 1 }], outputs: [{ templateId: 'spear', quantity: 1 }], laborHours: 18, minimumSkill: 20, description: 'Кузнец куёт наконечник и сажает его на древко.' },
  { name: 'Ковка меча', category: 'ремесло', profession: 'blacksmith', establishmentTypes: ['оружейная лавка', 'кузница'], inputs: [{ templateId: 'iron', quantity: 3 }, { templateId: 'charcoal', quantity: 2 }], outputs: [{ templateId: 'sword', quantity: 1, qualityBonus: 8 }], laborHours: 42, minimumSkill: 35, description: 'Клинок требует хорошего железа и долгой работы.' },
  { name: 'Земледельческие инструменты', category: 'ремесло', profession: 'toolmaker', establishmentTypes: ['инструментальная мастерская'], inputs: [{ templateId: 'iron', quantity: 2 }, { templateId: 'timber', quantity: 2 }], outputs: [{ templateId: 'sickle', quantity: 1 }, { templateId: 'hoe', quantity: 1 }], laborHours: 24, minimumSkill: 20, description: 'Мастер делает серпы и мотыги.' },
  { name: 'Инструменты шахтёра', category: 'ремесло', profession: 'toolmaker', establishmentTypes: ['инструментальная мастерская'], inputs: [{ templateId: 'iron', quantity: 2 }, { templateId: 'timber', quantity: 1 }], outputs: [{ templateId: 'pickaxe', quantity: 1 }], laborHours: 22, minimumSkill: 24, description: 'Мастер делает прочную кирку.' },
  { name: 'Инструменты текстильщиков', category: 'ремесло', profession: 'toolmaker', establishmentTypes: ['инструментальная мастерская'], inputs: [{ templateId: 'iron', quantity: 1 }, { templateId: 'timber', quantity: 1 }], outputs: [{ templateId: 'tailoring_kit', quantity: 1 }, { templateId: 'spindle', quantity: 1 }], laborHours: 18, minimumSkill: 18, description: 'Мастер делает ножницы, иглы, веретено и челнок.' },
  { name: 'Инструменты кожевников', category: 'ремесло', profession: 'toolmaker', establishmentTypes: ['инструментальная мастерская'], inputs: [{ templateId: 'iron', quantity: 1 }, { templateId: 'timber', quantity: 1 }], outputs: [{ templateId: 'tanner_knife', quantity: 1 }, { templateId: 'cobbler_tools', quantity: 1 }], laborHours: 20, minimumSkill: 20, description: 'Мастер делает ножи, шилья и колодки для кожи и обуви.' },
  { name: 'Инструменты плотника', category: 'ремесло', profession: 'toolmaker', establishmentTypes: ['инструментальная мастерская'], inputs: [{ templateId: 'iron', quantity: 2 }, { templateId: 'timber', quantity: 2 }], outputs: [{ templateId: 'wood_axe', quantity: 1 }, { templateId: 'carpenter_saw', quantity: 1 }], laborHours: 30, minimumSkill: 26, description: 'Мастер делает топор и пилу.' },
  { name: 'Изготовление стрел', category: 'ремесло', profession: 'blacksmith', establishmentTypes: ['арсенал', 'оружейная лавка', 'кузница'], inputs: [{ templateId: 'iron', quantity: .4 }, { templateId: 'timber', quantity: .6 }], outputs: [{ templateId: 'arrow_bundle', quantity: 3 }], laborHours: 12, minimumSkill: 16, description: 'Кузнец и древодел готовят колчаны стрел.' },
  { name: 'Изготовление арбалетов и болтов', category: 'ремесло', profession: 'blacksmith', establishmentTypes: ['арсенал', 'осадная мастерская', 'кузница'], inputs: [{ templateId: 'iron', quantity: 2 }, { templateId: 'planks', quantity: 2 }, { templateId: 'rope', quantity: 1 }], outputs: [{ templateId: 'crossbow', quantity: 1 }, { templateId: 'bolt_bundle', quantity: 2 }], laborHours: 34, minimumSkill: 32, description: 'Сложное метательное оружие собирается для гарнизонов.' },
  { name: 'Походные пайки', category: 'готовка', profession: 'cook', establishmentTypes: ['казарма', 'замковое хозяйство', 'пекарня'], inputs: [{ templateId: 'bread', quantity: 4 }, { templateId: 'smoked_meat', quantity: 1 }, { templateId: 'salt', quantity: .3 }], outputs: [{ templateId: 'military_rations', quantity: 8 }], laborHours: 8, minimumSkill: 10, description: 'Сухие пайки готовятся для похода и осады.' },
  { name: 'Походные палатки', category: 'ремесло', profession: 'tailor', establishmentTypes: ['портная мастерская', 'арсенал'], inputs: [{ templateId: 'linen_cloth', quantity: 6 }, { templateId: 'leather', quantity: 2 }, { templateId: 'timber', quantity: 1 }], outputs: [{ templateId: 'tent', quantity: 1 }], laborHours: 28, minimumSkill: 22, description: 'Портные шьют прочные армейские палатки.' },
  { name: 'Ремонтные детали обоза', category: 'ремесло', profession: 'carpenter', establishmentTypes: ['плотницкая мастерская', 'осадная мастерская'], inputs: [{ templateId: 'planks', quantity: 3 }, { templateId: 'iron', quantity: 1 }, { templateId: 'nails', quantity: 1 }], outputs: [{ templateId: 'wagon_parts', quantity: 1 }], laborHours: 24, minimumSkill: 22, description: 'Колёса, оси и скобы готовятся для военных повозок.' },
];

export function stableRecipeKey(name: string): string {
  return name.toLocaleLowerCase('ru-RU').normalize('NFKD').replace(/[^\p{L}\p{N}]+/gu, '-').replace(/^-+|-+$/g, '');
}

const outputTechnology = new Map<string, string>([
  ['milk', 'animal-husbandry'], ['eggs', 'animal-husbandry'], ['wool', 'animal-husbandry'], ['raw_hide', 'animal-husbandry'],
  ['smoked_meat', 'food-preservation'], ['salted_fish', 'food-preservation'],
  ['timber', 'carpentry'], ['planks', 'carpentry'], ['furniture', 'carpentry'], ['rope', 'textile-craft'],
  ['flax_fiber', 'textile-craft'], ['linen_thread', 'textile-craft'], ['linen_cloth', 'textile-craft'], ['wool_yarn', 'textile-craft'], ['wool_cloth', 'textile-craft'], ['cloth', 'textile-craft'], ['clothes', 'textile-craft'],
  ['linen_hood', 'textile-craft'], ['linen_shirt', 'textile-craft'], ['wool_tunic', 'textile-craft'], ['wool_trousers', 'textile-craft'], ['wool_cloak', 'textile-craft'],
  ['leather', 'textile-craft'], ['leather_shoes', 'textile-craft'], ['leather_gloves', 'textile-craft'],
  ['ale', 'fermentation'], ['wine', 'fermentation'],
  ['stone', 'masonry'], ['clay', 'masonry'], ['bricks', 'masonry'], ['lime', 'masonry'],
  ['iron', 'metalworking'], ['nails', 'metalworking'],
  ['tools', 'specialized-tools'], ['smith_hammer', 'specialized-tools'], ['sickle', 'specialized-tools'], ['hoe', 'specialized-tools'], ['pickaxe', 'specialized-tools'], ['wood_axe', 'specialized-tools'], ['carpenter_saw', 'specialized-tools'], ['tailoring_kit', 'specialized-tools'], ['spindle', 'specialized-tools'], ['tanner_knife', 'specialized-tools'], ['cobbler_tools', 'specialized-tools'],
  ['weapon', 'metalworking'], ['spear', 'metalworking'], ['sword', 'metalworking'], ['iron_helmet', 'advanced-armoring'], ['gambeson', 'advanced-armoring'], ['leather_armor', 'advanced-armoring'], ['wooden_shield', 'advanced-armoring'], ['longbow', 'advanced-armoring'],
  ['herbal_medicine', 'formal-medicine'],
]);

function technologyForRecipe(recipe: Omit<ProductionRecipe, 'id' | 'key'>): string | undefined {
  const outputIds = recipe.outputs.map(output => output.templateId);
  const technologies = outputIds.map(id => outputTechnology.get(id)).filter((id): id is string => Boolean(id));
  if (technologies.includes('advanced-armoring')) return 'advanced-armoring';
  if (technologies.includes('formal-medicine')) return 'formal-medicine';
  if (technologies.includes('specialized-tools')) return 'specialized-tools';
  if (technologies.includes('metalworking')) return 'metalworking';
  if (technologies.includes('masonry')) return 'masonry';
  if (technologies.includes('fermentation')) return 'fermentation';
  if (technologies.includes('textile-craft')) return 'textile-craft';
  if (technologies.includes('carpentry')) return 'carpentry';
  if (technologies.includes('food-preservation')) return 'food-preservation';
  if (technologies.includes('animal-husbandry')) return 'animal-husbandry';
  if (outputIds.some(id => ['flour', 'bread'].includes(id))) return 'mechanical-milling';
  if (recipe.category === 'добыча' || outputIds.some(id => ['grain', 'wheat', 'barley', 'rye', 'flax', 'vegetables', 'fruit', 'straw'].includes(id))) return 'settled-agriculture';
  return undefined;
}

export const CORE_RECIPES: RecipeDefinition[] = RAW_RECIPES.map(recipe => ({
  ...recipe,
  key: stableRecipeKey(recipe.name),
  requiredTechnologyId: technologyForRecipe(recipe),
}));
