import type { ResourceDefinition } from '../civilizationTypes';

export const CORE_RESOURCES: ResourceDefinition[] = [
  { id: 'grain', name: 'зерно', category: 'сырьё', material: 'зерно', unit: 'мешок', weight: 25, perishability: 18, value: 7 },
  { id: 'flour', name: 'мука', category: 'сырьё', material: 'мука', unit: 'мешок', weight: 20, perishability: 8, value: 11 },
  { id: 'bread', name: 'хлеб', category: 'еда', material: 'выпечка', unit: 'буханка', weight: .7, perishability: 1, value: 2.2 },
  { id: 'vegetables', name: 'овощи и коренья', category: 'еда', material: 'растительная пища', unit: 'корзина', weight: 8, perishability: 3, value: 5 },
  { id: 'fruit', name: 'фрукты и ягоды', category: 'еда', material: 'растительная пища', unit: 'корзина', weight: 6, perishability: 2, value: 6 },
  { id: 'meat', name: 'свежее мясо', category: 'еда', material: 'мясо', unit: 'туша', weight: 18, perishability: 1, value: 14 },
  { id: 'smoked_meat', name: 'копчёное мясо', category: 'еда', material: 'мясо', unit: 'связка', weight: 6, perishability: 10, value: 13 },
  { id: 'fish', name: 'свежая рыба', category: 'еда', material: 'рыба', unit: 'корзина', weight: 10, perishability: 1, value: 9 },
  { id: 'salted_fish', name: 'солёная рыба', category: 'еда', material: 'рыба', unit: 'бочонок', weight: 14, perishability: 12, value: 16 },
  { id: 'milk', name: 'молоко', category: 'еда', material: 'молоко', unit: 'кувшин', weight: 2, perishability: 1, value: 2 },
  { id: 'eggs', name: 'яйца', category: 'еда', material: 'яйца', unit: 'десяток', weight: .7, perishability: 2, value: 2.4 },
  { id: 'stew', name: 'горячая похлёбка', category: 'еда', material: 'готовое блюдо', unit: 'порция', weight: .6, perishability: 1, value: 2.8 },
  { id: 'roast', name: 'жаркое', category: 'еда', material: 'готовое блюдо', unit: 'порция', weight: .7, perishability: 1, value: 4.4 },
  { id: 'ale', name: 'эль', category: 'напиток', material: 'ячменный напиток', unit: 'кружка', weight: .6, perishability: 8, value: 1.7 },
  { id: 'wine', name: 'вино', category: 'напиток', material: 'виноградный напиток', unit: 'бутыль', weight: 1.2, perishability: 60, value: 8 },
  { id: 'water', name: 'чистая вода', category: 'напиток', material: 'вода', unit: 'бурдюк', weight: 3, perishability: 2, value: .4 },
  { id: 'firewood', name: 'дрова', category: 'топливо', material: 'древесина', unit: 'вязанка', weight: 12, perishability: 0, value: 3 },
  { id: 'charcoal', name: 'древесный уголь', category: 'топливо', material: 'уголь', unit: 'мешок', weight: 10, perishability: 0, value: 6 },
  { id: 'timber', name: 'строевая древесина', category: 'сырьё', material: 'древесина', unit: 'бревно', weight: 45, perishability: 0, value: 10 },
  { id: 'stone', name: 'тёсаный камень', category: 'сырьё', material: 'камень', unit: 'блок', weight: 35, perishability: 0, value: 8 },
  { id: 'iron_ore', name: 'железная руда', category: 'сырьё', material: 'руда', unit: 'корзина', weight: 30, perishability: 0, value: 9 },
  { id: 'iron', name: 'железная крица', category: 'сырьё', material: 'железо', unit: 'слиток', weight: 7, perishability: 0, value: 19 },
  { id: 'wool', name: 'шерсть', category: 'сырьё', material: 'шерсть', unit: 'тюк', weight: 8, perishability: 0, value: 8 },
  { id: 'cloth', name: 'ткань', category: 'сырьё', material: 'ткань', unit: 'рулон', weight: 4, perishability: 0, value: 18 },
  { id: 'clothes', name: 'простая одежда', category: 'одежда', material: 'ткань', unit: 'комплект', weight: 2, perishability: 0, value: 26 },
  { id: 'tools', name: 'рабочие инструменты', category: 'инструмент', material: 'железо и дерево', unit: 'набор', weight: 5, perishability: 0, value: 34 },
  { id: 'weapon', name: 'обычное оружие', category: 'оружие', material: 'железо и дерево', unit: 'штука', weight: 3, perishability: 0, value: 48 },
  { id: 'furniture', name: 'простая мебель', category: 'мебель', material: 'древесина', unit: 'предмет', weight: 16, perishability: 0, value: 22 },
  { id: 'herbal_medicine', name: 'лечебный отвар', category: 'лекарство', material: 'травы', unit: 'склянка', weight: .3, perishability: 4, value: 12 },
  { id: 'salt', name: 'соль', category: 'сырьё', material: 'соль', unit: 'мешочек', weight: 2, perishability: 0, value: 4 },
  { id: 'wheat_seed', name: 'семена пшеницы', category: 'семена', material: 'семена', unit: 'мера', weight: 1, perishability: 24, value: 4 },
  { id: 'barley_seed', name: 'семена ячменя', category: 'семена', material: 'семена', unit: 'мера', weight: 1, perishability: 24, value: 4 },
  { id: 'rye_seed', name: 'семена ржи', category: 'семена', material: 'семена', unit: 'мера', weight: 1, perishability: 24, value: 4 },
  { id: 'flax_seed', name: 'семена льна', category: 'семена', material: 'семена', unit: 'мера', weight: .8, perishability: 24, value: 5 },
  { id: 'vegetable_seed', name: 'семена овощей', category: 'семена', material: 'семена', unit: 'мешочек', weight: .6, perishability: 18, value: 5 },
  { id: 'wheat', name: 'пшеница', category: 'сырьё', material: 'зерно', unit: 'мешок', weight: 25, perishability: 18, value: 8 },
  { id: 'barley', name: 'ячмень', category: 'сырьё', material: 'зерно', unit: 'мешок', weight: 25, perishability: 18, value: 7 },
  { id: 'rye', name: 'рожь', category: 'сырьё', material: 'зерно', unit: 'мешок', weight: 25, perishability: 20, value: 7 },
  { id: 'flax', name: 'лён', category: 'сырьё', material: 'растительное волокно', unit: 'сноп', weight: 8, perishability: 10, value: 9 },
  { id: 'straw', name: 'солома', category: 'сырьё', material: 'солома', unit: 'тюк', weight: 7, perishability: 18, value: 3 },
  { id: 'planks', name: 'доски', category: 'сырьё', material: 'древесина', unit: 'связка', weight: 18, perishability: 0, value: 15 },
  { id: 'clay', name: 'глина', category: 'сырьё', material: 'глина', unit: 'корзина', weight: 28, perishability: 0, value: 5 },
  { id: 'bricks', name: 'обожжённый кирпич', category: 'сырьё', material: 'керамика', unit: 'партия', weight: 35, perishability: 0, value: 16 },
  { id: 'lime', name: 'строительная известь', category: 'сырьё', material: 'известь', unit: 'мешок', weight: 20, perishability: 0, value: 12 },
  { id: 'nails', name: 'железные гвозди', category: 'сырьё', material: 'железо', unit: 'короб', weight: 4, perishability: 0, value: 15 },
  { id: 'rope', name: 'льняная верёвка', category: 'инструмент', material: 'лён', unit: 'моток', weight: 3, perishability: 0, value: 14, toolType: 'верёвка', maxCondition: 90 },
  { id: 'flax_fiber', name: 'льняное волокно', category: 'сырьё', material: 'лён', unit: 'тюк', weight: 5, perishability: 0, value: 11 },
  { id: 'linen_thread', name: 'льняная нить', category: 'сырьё', material: 'лён', unit: 'моток', weight: 1.5, perishability: 0, value: 15 },
  { id: 'linen_cloth', name: 'льняная ткань', category: 'сырьё', material: 'лён', unit: 'рулон', weight: 3, perishability: 0, value: 23 },
  { id: 'wool_yarn', name: 'шерстяная пряжа', category: 'сырьё', material: 'шерсть', unit: 'моток', weight: 2, perishability: 0, value: 14 },
  { id: 'wool_cloth', name: 'шерстяная ткань', category: 'сырьё', material: 'шерсть', unit: 'рулон', weight: 4, perishability: 0, value: 28 },
  { id: 'raw_hide', name: 'сырая шкура', category: 'сырьё', material: 'шкура', unit: 'шкура', weight: 6, perishability: 2, value: 10 },
  { id: 'leather', name: 'дублёная кожа', category: 'сырьё', material: 'кожа', unit: 'лист', weight: 4, perishability: 0, value: 22 },
  { id: 'dye_blue', name: 'синий краситель', category: 'краситель', material: 'вайда', unit: 'мешочек', weight: .3, perishability: 24, value: 18, dye: 'синий' },
  { id: 'dye_red', name: 'красный краситель', category: 'краситель', material: 'марена', unit: 'мешочек', weight: .3, perishability: 24, value: 21, dye: 'красный' },
  { id: 'dye_yellow', name: 'жёлтый краситель', category: 'краситель', material: 'резеда', unit: 'мешочек', weight: .3, perishability: 24, value: 14, dye: 'жёлтый' },
  { id: 'dye_brown', name: 'коричневый краситель', category: 'краситель', material: 'кора и орех', unit: 'мешочек', weight: .4, perishability: 30, value: 9, dye: 'коричневый' },
  { id: 'dye_purple', name: 'пурпурный краситель', category: 'краситель', material: 'редкий пигмент', unit: 'склянка', weight: .2, perishability: 36, value: 90, dye: 'пурпурный' },
  { id: 'linen_hood', name: 'льняной капюшон', category: 'одежда', material: 'лён', unit: 'штука', weight: .3, perishability: 0, value: 11, equipmentSlot: 'head', warmth: 5, armor: 0, maxCondition: 70 },
  { id: 'linen_shirt', name: 'льняная рубаха', category: 'одежда', material: 'лён', unit: 'штука', weight: .7, perishability: 0, value: 18, equipmentSlot: 'body', warmth: 7, armor: 0, maxCondition: 75 },
  { id: 'wool_tunic', name: 'шерстяная туника', category: 'одежда', material: 'шерсть', unit: 'штука', weight: 1.1, perishability: 0, value: 30, equipmentSlot: 'body', warmth: 18, armor: 1, maxCondition: 85 },
  { id: 'wool_trousers', name: 'шерстяные штаны', category: 'одежда', material: 'шерсть', unit: 'штука', weight: .8, perishability: 0, value: 22, equipmentSlot: 'legs', warmth: 12, armor: 0, maxCondition: 80 },
  { id: 'leather_shoes', name: 'кожаные башмаки', category: 'одежда', material: 'кожа', unit: 'пара', weight: .9, perishability: 0, value: 27, equipmentSlot: 'feet', warmth: 7, armor: 1, maxCondition: 90 },
  { id: 'leather_gloves', name: 'кожаные перчатки', category: 'одежда', material: 'кожа', unit: 'пара', weight: .4, perishability: 0, value: 19, equipmentSlot: 'hands', warmth: 6, armor: 1, maxCondition: 85 },
  { id: 'wool_cloak', name: 'шерстяной плащ', category: 'одежда', material: 'шерсть', unit: 'штука', weight: 1.5, perishability: 0, value: 38, equipmentSlot: 'cloak', warmth: 22, armor: 1, maxCondition: 90 },
  { id: 'royal_cloak', name: 'пурпурный придворный плащ', category: 'одежда', material: 'тонкая шерсть', unit: 'штука', weight: 1.2, perishability: 0, value: 180, equipmentSlot: 'cloak', dye: 'пурпурный', warmth: 20, armor: 1, maxCondition: 100 },
  { id: 'padded_cap', name: 'стёганая шапка', category: 'броня', material: 'лён и шерсть', unit: 'штука', weight: .8, perishability: 0, value: 24, equipmentSlot: 'head', warmth: 10, armor: 3, maxCondition: 90 },
  { id: 'gambeson', name: 'гамбезон', category: 'броня', material: 'стёганый лён', unit: 'штука', weight: 5, perishability: 0, value: 70, equipmentSlot: 'body', warmth: 18, armor: 7, maxCondition: 100 },
  { id: 'leather_armor', name: 'кожаный доспех', category: 'броня', material: 'кожа', unit: 'штука', weight: 6, perishability: 0, value: 95, equipmentSlot: 'body', warmth: 12, armor: 10, maxCondition: 110 },
  { id: 'chainmail', name: 'кольчуга', category: 'броня', material: 'железо', unit: 'штука', weight: 11, perishability: 0, value: 230, equipmentSlot: 'body', warmth: 4, armor: 18, maxCondition: 125 },
  { id: 'iron_helmet', name: 'железный шлем', category: 'броня', material: 'железо', unit: 'штука', weight: 2.5, perishability: 0, value: 85, equipmentSlot: 'head', warmth: 2, armor: 14, maxCondition: 120 },
  { id: 'wooden_shield', name: 'деревянный щит', category: 'броня', material: 'дерево и кожа', unit: 'штука', weight: 4, perishability: 0, value: 38, equipmentSlot: 'offHand', armor: 8, maxCondition: 95 },
  { id: 'knife', name: 'рабочий нож', category: 'оружие', material: 'железо', unit: 'штука', weight: .5, perishability: 0, value: 18, equipmentSlot: 'mainHand', damage: 4, maxCondition: 85 },
  { id: 'club', name: 'дубина', category: 'оружие', material: 'дерево', unit: 'штука', weight: 2, perishability: 0, value: 5, equipmentSlot: 'mainHand', damage: 5, maxCondition: 70 },
  { id: 'spear', name: 'копьё', category: 'оружие', material: 'железо и дерево', unit: 'штука', weight: 2.5, perishability: 0, value: 34, equipmentSlot: 'mainHand', damage: 8, maxCondition: 95 },
  { id: 'sword', name: 'железный меч', category: 'оружие', material: 'железо', unit: 'штука', weight: 1.5, perishability: 0, value: 110, equipmentSlot: 'mainHand', damage: 11, maxCondition: 115 },
  { id: 'longbow', name: 'длинный лук', category: 'оружие', material: 'дерево и сухожилия', unit: 'штука', weight: 1.2, perishability: 0, value: 65, equipmentSlot: 'mainHand', damage: 9, maxCondition: 90 },
  { id: 'sickle', name: 'серп', category: 'инструмент', material: 'железо и дерево', unit: 'штука', weight: 1, perishability: 0, value: 22, equipmentSlot: 'workTool', toolType: 'земледелие', requiredProfession: 'farmer', maxCondition: 90 },
  { id: 'hoe', name: 'мотыга', category: 'инструмент', material: 'железо и дерево', unit: 'штука', weight: 2.5, perishability: 0, value: 28, equipmentSlot: 'workTool', toolType: 'земледелие', requiredProfession: 'farmer', maxCondition: 95 },
  { id: 'pickaxe', name: 'кирка', category: 'инструмент', material: 'железо и дерево', unit: 'штука', weight: 4, perishability: 0, value: 46, equipmentSlot: 'workTool', toolType: 'добыча', requiredProfession: 'miner', maxCondition: 105 },
  { id: 'wood_axe', name: 'лесной топор', category: 'инструмент', material: 'железо и дерево', unit: 'штука', weight: 2.8, perishability: 0, value: 42, equipmentSlot: 'workTool', toolType: 'лесозаготовка', requiredProfession: 'carpenter', maxCondition: 100 },
  { id: 'smith_hammer', name: 'кузнечный молот', category: 'инструмент', material: 'железо и дерево', unit: 'штука', weight: 3.5, perishability: 0, value: 55, equipmentSlot: 'workTool', toolType: 'кузнечное дело', requiredProfession: 'blacksmith', maxCondition: 115 },
  { id: 'carpenter_saw', name: 'плотницкая пила', category: 'инструмент', material: 'железо и дерево', unit: 'штука', weight: 2, perishability: 0, value: 48, equipmentSlot: 'workTool', toolType: 'плотницкое дело', requiredProfession: 'carpenter', maxCondition: 95 },
  { id: 'fishing_net', name: 'рыболовная сеть', category: 'инструмент', material: 'лён', unit: 'штука', weight: 4, perishability: 0, value: 36, equipmentSlot: 'workTool', toolType: 'рыболовство', requiredProfession: 'fisher', maxCondition: 80 },
  { id: 'herb_knife', name: 'нож травника', category: 'инструмент', material: 'железо и дерево', unit: 'штука', weight: .4, perishability: 0, value: 19, equipmentSlot: 'workTool', toolType: 'собирательство', requiredProfession: 'herbalist', maxCondition: 80 },
  { id: 'mortar', name: 'ступка и пестик', category: 'инструмент', material: 'камень', unit: 'набор', weight: 3, perishability: 0, value: 31, equipmentSlot: 'workTool', toolType: 'алхимия', requiredProfession: 'healer', maxCondition: 110 },
  { id: 'tailoring_kit', name: 'набор портного', category: 'инструмент', material: 'железо, дерево и нить', unit: 'набор', weight: 1.2, perishability: 0, value: 39, equipmentSlot: 'workTool', toolType: 'портняжное дело', requiredProfession: 'tailor', maxCondition: 90 },
  { id: 'spindle', name: 'веретено и челнок', category: 'инструмент', material: 'дерево', unit: 'набор', weight: .8, perishability: 0, value: 18, equipmentSlot: 'workTool', toolType: 'ткачество', requiredProfession: 'weaver', maxCondition: 80 },
  { id: 'tanner_knife', name: 'нож кожевника', category: 'инструмент', material: 'железо и дерево', unit: 'штука', weight: .8, perishability: 0, value: 27, equipmentSlot: 'workTool', toolType: 'кожевенное дело', requiredProfession: 'tanner', maxCondition: 90 },
  { id: 'crossbow', name: 'арбалет', category: 'оружие', material: 'дерево и железо', unit: 'штука', weight: 4.2, perishability: 0, value: 105, equipmentSlot: 'mainHand', damage: 13, maxCondition: 110 },
  { id: 'arrow_bundle', name: 'колчан стрел', category: 'оружие', material: 'дерево, железо и перо', unit: 'колчан', weight: 2.2, perishability: 0, value: 22, maxCondition: 100 },
  { id: 'bolt_bundle', name: 'связка арбалетных болтов', category: 'оружие', material: 'дерево и железо', unit: 'связка', weight: 2.8, perishability: 0, value: 28, maxCondition: 100 },
  { id: 'lance', name: 'кавалерийское копьё', category: 'оружие', material: 'железо и дерево', unit: 'штука', weight: 4.5, perishability: 0, value: 62, equipmentSlot: 'mainHand', damage: 14, maxCondition: 105 },
  { id: 'mace', name: 'железная булава', category: 'оружие', material: 'железо и дерево', unit: 'штука', weight: 2.4, perishability: 0, value: 78, equipmentSlot: 'mainHand', damage: 12, maxCondition: 120 },
  { id: 'bandages', name: 'чистые перевязочные материалы', category: 'лекарство', material: 'лён', unit: 'набор', weight: .6, perishability: 18, value: 10 },
  { id: 'military_rations', name: 'походный паёк', category: 'еда', material: 'сухари, соль и сушёное мясо', unit: 'паёк', weight: 1.1, perishability: 12, value: 4.5 },
  { id: 'tent', name: 'походная палатка', category: 'предмет быта', material: 'лён, кожа и дерево', unit: 'штука', weight: 18, perishability: 0, value: 65, maxCondition: 100 },
  { id: 'wagon_parts', name: 'детали для повозок', category: 'инструмент', material: 'дерево и железо', unit: 'комплект', weight: 26, perishability: 0, value: 58, toolType: 'ремонт обоза', maxCondition: 110 },
  { id: 'horse_feed', name: 'корм для лошадей', category: 'сырьё', material: 'овёс и сено', unit: 'мешок', weight: 20, perishability: 8, value: 6 },
  { id: 'cobbler_tools', name: 'инструменты сапожника', category: 'инструмент', material: 'железо и дерево', unit: 'набор', weight: 1.4, perishability: 0, value: 36, equipmentSlot: 'workTool', toolType: 'сапожное дело', requiredProfession: 'cobbler', maxCondition: 95 },
];
